server:
  port: 50700
  tomcat.threads.max: 20

security:
  authentication:
    enabled: true

hapi:
  fhir:
    server:
      path: /fhir/*
    rest:
      server-name: example-fhir-facade
      server-version: 1.0.0
      implementation-description: example-fhir-facade
      default-response-encoding: xml
      e-tag-support: enabled
      default-pretty-print: true
    validation:
      enabled: true
      request-only: true

management:
  endpoints:
    web:
      exposure:
        include: "info,health"
  endpoint:
    health:
      show-details: always

#log levels
logging.level.root: "WARN"
logging.level.org.goafabric: "INFO"

logging.level.org.springframework: "INFO"
logging.level.org.flywaydb.core: "INFO"
logging.level.org.hibernate.SQL: "INFO"

#logging.pattern.console: "%white(%d{ISO8601}) %highlight(%-5level) [%blue(%t)] %yellow(%C{1.}): %msg%n%throwable"
