apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.fullname" . }}-secret
  labels:
    {{- include "application.labels" . | nindent 4 }}

data:
  adapter.personservice.user: WVdSdGFXND0=
  adapter.personservice.password: WVdSdGFXND0=