replicaCount: 1

ingress:
  paths: /fhir
  enabled: true
  authentication: basic

image:
  repository: "goafabric/fhir-facade"
  pullPolicy: IfNotPresent
  pullSecrets: 

podAnnotations:
  linkerd.io/inject: enabled
  sidecar.istio.io/inject: "true"

resourcesAnnotations:
  resources:
    requests:
      memory: 128M
      cpu: 250m

  command: ["java", "-Xms128M", "-Xmx128M", "-cp", "/app/resources:/app/classes:/app/libs/*", "org.goafabric.fhir.Application"]

readinessProbe:
  initialDelaySeconds: 2

service:
  type: ClusterIP
  port: 8080
